Unpin rake version
Rake 10.x produces the following error with ruby 3.2:

    rake aborted!
    NoMethodError: undefined method `=~' for #<Proc:0x0000000105127e78
    .gem/ruby/3.2.0/gems/rake-10.5.0/lib/rake/application.rb:393 (lambda)>

I'm not sure exactly why this is, but I can no longer replicate the
error that caused rake to be pinned to version 10.x in 5e46ecd, so I'm
unpinning it again to fix the build.